import { Geist, Geist_Mono,Rancho,Londrina_Solid } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//using this in nav header
export const rancho = Rancho({     
  subsets: ["latin"],
  weight: "400",
});

export const londrina = Londrina_Solid({     
  subsets: ["latin"],
   weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-[url('/images/nolimitbackground.png')] bg-no-repeat bg-cover min-h-full flex flex-col">{children}</body>
    </html>
  );
}
